In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import numpy as np

In [5]:
data = pd.read_csv("E:/Alsayad Electronics/Downloads/PlayTennis.csv")
data.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [8]:
from sklearn.preprocessing import OrdinalEncoder
outlook_encoder = OrdinalEncoder()
data['Outlook'] = outlook_encoder.fit_transform(data[['Outlook']])

temp_encoder = OrdinalEncoder()
data['Temperature'] = outlook_encoder.fit_transform(data[['Temperature']])

him_encoder = OrdinalEncoder()
data['Humidity'] = outlook_encoder.fit_transform(data[['Humidity']])

windy_encoder = OrdinalEncoder()
data['Wind'] = outlook_encoder.fit_transform(data[['Wind']])

p_tennis_encoder = OrdinalEncoder()
data['Play Tennis'] = outlook_encoder.fit_transform(data[['Play Tennis']])

In [ ]:
dat

    Outlook  Temperature  Humidity  Wind  Play Tennis
0       2.0          1.0       0.0   1.0          0.0
1       2.0          1.0       0.0   0.0          0.0
2       0.0          1.0       0.0   1.0          1.0
3       1.0          2.0       0.0   1.0          1.0
4       1.0          0.0       1.0   1.0          1.0
5       1.0          0.0       1.0   0.0          0.0
6       0.0          0.0       1.0   0.0          1.0
7       2.0          2.0       0.0   1.0          0.0
8       2.0          0.0       1.0   1.0          1.0
9       1.0          2.0       1.0   1.0          1.0
10      2.0          2.0       1.0   0.0          1.0
11      0.0          2.0       0.0   0.0          1.0
12      0.0          1.0       1.0   1.0          1.0
13      1.0          2.0       0.0   0.0          0.0